#!/bin/sh -e

for file in *.patch; do
  patch -Np1 -i $file
done

./configure \
    --prefix=/usr \
    --sysconfdir=/etc \
    --disable-nls \
    --disable-librsvg \
    --disable-imlib2 \
    --disable-session-management

make
make -j1 DESTDIR="$1" install
